application: kemonotag
version: 2
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /testing
  script: googlespread.app
  login: admin

- url: /reload
  script: webapp.app
  login: admin

- url: /reloadtask
  script: webapp.app
  login: admin

- url: /rtag
  script: webapp.app
  login: admin

- url: /rtagtask
  script: webapp.app
  login: admin

- url: /databackup
  script: webapp.app
  login: admin

- url: /graph
  static_files: d3/index.html
  upload: d3/index.html

- url: /graphdata
  static_files: d3/graph.json
  upload: d3/graph.json

- url: /script
  static_files: d3/script.js
  upload: d3/script.js

- url: /
  script: webapp.app

- url: /.*
  script: webapp.app



libraries:
- name: django
  version: latest

- name: numpy
  version: "1.6.1"

- name: matplotlib
  version: latest